#!/usr/bin/env bash
# Display "Best School" 8 times plus "badluck" and "goodluck" at iteration 4 and 8 respectively
x=1
while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
    fi
    ((x++))
done